# basic treatments!
BasicTreatment.create!(description: 'Periodontia')
BasicTreatment.create!(description: 'Dentística')
BasicTreatment.create!(description: 'Endodontia')
BasicTreatment.create!(description: 'Ortodontia')
BasicTreatment.create!(description: 'Prótese Total')
BasicTreatment.create!(description: 'Prótese Parcial Removível')
BasicTreatment.create!(description: 'Prótese Fixa')
BasicTreatment.create!(description: 'Odontopediatria')
BasicTreatment.create!(description: 'Cirurgia I')
BasicTreatment.create!(description: 'Cirurgia II')
BasicTreatment.create!(description: 'Outros')
BasicTreatment.create!(description: 'Especialização - Implantodontia')
